--- 
title: "Predictive Modeling with Trees"
author: "Homer White"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
knit: "bookdown::render_book"
output:
  bookdown::gitbook:
    lib_dir: "book_assets"
  bookdown::pdf_book:
    keep_tex: yes
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: homerhanumat/tigerTree
description: "These are course notes for a unit on trees and random forests."
---

# Introduction {#introduction}

```{r  include=FALSE}
library(knitr)
opts_chunk$set(tidy=FALSE)
library(tigerstats)
library(tigerTree)
```

Let's see what we can do.  Let's cite [@statlearn].

## Graphs {#graphs}

Can we really make a graph with captions, and refer to it?

```{r echo = FALSE}
trMod <- tree(sex ~ ., data = m111survey)
```


```{r ch1sextree, echo = FALSE, fig.align = "center", fig.cap = "Default classification tree to predict sex on the basis of other variables in the `m111survey` data frame."}
plot(trMod); text(trMod)
```

As Figure \@ref(fig:ch1sextree) shows ...

## Tables {#tables}

Hmm, let's make a table.^[Tables are fun.]

```{r ch1sexconfusion, echo = FALSE}
trySex <- tryTree(trMod, testSet = m111survey, 
                  truth = m111survey$sex, printOut = FALSE)
kable(trySex$confusion, caption = "Confusion matrix for the tree model.")
```

As Table \@ref(tab:ch1sexconfusion) shows ...

We can learn about trees in Chapter \@ref(randomforests).


